version: "3"
services: 
  loki:
    image: "grafana/loki:1.5.0" 
    container_name: "loki"
    restart: "always"
    volumes: 
      - "/etc/localtime:/etc/localtime"
      - "./etc:/etc/loki"
      - "./loki:/loki"
    ports: 
      - "3100:3100"
    command: "-config.file=/etc/loki/local-config.yaml"